# Generated by Django 3.0.3 on 2020-02-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0003_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('python', models.TextField()),
                ('sap', models.TextField()),
                ('matlab', models.TextField()),
                ('dba', models.TextField()),
                ('plsql', models.TextField()),
                ('rpa', models.TextField()),
                ('salesforce', models.TextField()),
            ],
        ),
    ]
