# Generated by Django 3.0.3 on 2020-11-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OdiBattingRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('runs', models.IntegerField()),
                ('fifties', models.IntegerField()),
                ('centuries', models.IntegerField()),
                ('double_centuries', models.IntegerField()),
            ],
        ),
    ]
