# Generated by Django 3.1.1 on 2020-10-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0002_student_studentinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='mobile',
            field=models.BigIntegerField(),
        ),
    ]
