# Generated by Django 3.0.3 on 2020-10-05 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='branch',
            new_name='branch_id',
        ),
    ]
