# Generated by Django 3.0.3 on 2020-10-05 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_auto_20201005_1050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='branch_id',
            new_name='branch',
        ),
    ]
