# Generated by Django 3.0.3 on 2020-10-05 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0005_auto_20201005_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='account_id',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='withdraw',
            old_name='account_id',
            new_name='account',
        ),
    ]
