# Generated by Django 3.0.3 on 2020-10-05 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0006_auto_20201005_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bankapp.Account', unique=True),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bankapp.Account', unique=True),
        ),
    ]
