# Generated by Django 3.1.4 on 2020-12-09 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('many21', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={},
        ),
    ]
