# Generated by Django 3.0.3 on 2020-11-24 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=24)),
                ('page_type', models.CharField(max_length=256)),
                ('page_publish', models.DateField()),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='OneToOne.Creator')),
            ],
        ),
    ]
