# Generated by Django 3.0.3 on 2020-02-20 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testappS', '0005_auto_20200220_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='dob',
        ),
    ]
