# Generated by Django 3.0.3 on 2020-05-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.BigIntegerField(max_length=10)),
                ('password', models.TextField()),
                ('confirm_password', models.TextField()),
                ('recovery_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
