# Generated by Django 3.0.3 on 2020-05-22 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('middle_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('course', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('phone', models.BigIntegerField()),
                ('address', models.TextField()),
                ('password', models.CharField(max_length=10)),
                ('renter_password', models.CharField(max_length=10)),
            ],
        ),
    ]
