# Generated by Django 3.0.3 on 2020-12-03 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BowlingRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('wickets', models.IntegerField()),
                ('best', models.IntegerField()),
                ('five', models.IntegerField()),
            ],
        ),
    ]
